### ISSUE TITLE
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1

### ISSUE THREAD

**Issue by dodanghoanganh** [kelciour/batch-download-pictures-from-google-images#1]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-06 10:05:45

C:\Users\xyz\AppData\Roaming\Anki2\addons21\batch_download_pictures_from_google_images\vendor\PIL\TiffImagePlugin.py:788: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))

**Comment by kelciour** [comment]
Thank you for the report. I've added a fix for it and uploaded a new beta - https://github.com/kelciour/batch-download-pictures-from-google-images/releases/tag/v0.1.1-beta5

**Comment by dodanghoanganh** [comment]
Many thanks! <3 (y)

**Comment by dodanghoanganh** [comment]
I've just tested it. It's worked great! I would like to say thank you very much.
