### ISSUE TITLE
"batch-download-pictures-from-google-images" in ANKI 2.1.54 not work.

### ISSUE THREAD

**Issue by ladhor** [kelciour/batch-download-pictures-from-google-images#10]
Hi, addon "batch-download-pictures-from-google-images" in ANKI 2.1.54 not work.

![image](https://user-images.githubusercontent.com/116520757/197416273-c0844b55-1a37-403b-bf26-5c318c71c129.png)

**Comment by ngtuonghy** [comment]
@ladhor 
![Screenshot (3)](https://user-images.githubusercontent.com/116539745/197453876-2ab25185-91d2-45b3-b7dd-c9bae2c100de.png)
me too

**Comment by colinnevis** [comment]
I am also getting this same error on Mac on Version ⁨2.1.54

**Comment by Supremerino** [comment]
Getting the same error.

**Comment by kelciour** [comment]
The add-on was updated recently and should work with the latest Anki version.
