### ISSUE TITLE
Add-on crashing on anki 2.1.54

### ISSUE THREAD

**Issue by NightGliderz** [kelciour/batch-download-pictures-from-google-images#12]
Hello, the add-on crashes on my anki desktop version 2.1.54. I attached a result of the debug consode below.

Thanks!

[debug output.txt](https://github.com/kelciour/batch-download-pictures-from-google-images/files/10166448/debug.output.txt)

**Comment by kelciour** [comment]
The latest compatible version is Anki 2.1.49

The add-on needs to be updated to work on Anki 2.1.50+.

It's unknown when/if it happens.

**Comment by kelciour** [comment]
If the error message was about PIL, it might be fixed by replacing the `vendor/PIL` folder in the add-on's folder with the `PIL` folder from the extracted .whl with `cp39` from https://pypi.org/project/Pillow/#files

**Comment by NightGliderz** [comment]
I tried that but that is not working.

Only downgrading to 2.1.49 is making the add-on work properly. 

Thanks for the suggestion by the way. It's a very useful add-on that I frequently use. I hope you eventually get to update it for the current Anki version.

**Comment by kelciour** [comment]
The add-on was recently updated to support the latest Anki version and I'm closing the issue.
