### ISSUE TITLE
The field Image does not filled (Anki 2.1.15)

### ISSUE THREAD

**Issue by vitalysennikov** [kelciour/batch-download-pictures-from-google-images#13]
Anki Version 2.1.15 (442df9d6), Qt 5.15.2 PyQt 5.15.6

I use this version of Anki because some addons don't work in higher versions. But addon batch-download-pictures-from-google-images worked fine early.

When I run now I don't get error messages, it seems ok, but field don't filled. See screenshots, maybe I did mistake somewhere in settings.

![Screen_2022-12-15 07-29-49](https://user-images.githubusercontent.com/52925644/207774557-351dba3e-2907-49f3-8d40-2a491cbcdcde.png)
![Screen_2022-12-15 07-30-40](https://user-images.githubusercontent.com/52925644/207774594-651e0fcc-2865-4a2a-bf82-0abea43cda74.png)
![Screen_2022-12-15 07-31-09](https://user-images.githubusercontent.com/52925644/207774631-650a0d4a-3224-46c5-9754-eaa793609727.png)
![Screen_2022-12-15 07-31-55](https://user-images.githubusercontent.com/52925644/207774633-dfbccb0d-2f24-4c13-ba01-e894fddd9ea6.png)

I go to steps:

> The add-on was updated recently and it seems to work for me. If it doesn't work, maybe run this minimal example in the debug console - https://gist.github.com/kelciour/86bfa1bbcc256fbaa780ab725da14714 - copy the output and create a new issue at https://github.com/kelciour/batch-download-pictures-from-google-images/issues
> 
> https://docs.ankiweb.net/misc.html?highlight=debug#debug-console

[debug-console.txt](https://github.com/kelciour/batch-download-pictures-from-google-images/files/10233785/debug-console.txt)

**Comment by kelciour** [comment]
I patched it with a few recent commits, updated it on AnkiWeb and the add-on might work now.
