### ISSUE TITLE
Endless "Processing..." on Anki 2.1.49

### ISSUE THREAD

**Issue by pianoplayer15** [kelciour/batch-download-pictures-from-google-images#14]
![Screenshot 2023-02-23 151100](https://user-images.githubusercontent.com/62180101/220931743-f5366026-4e43-4ed8-baec-a89bff5bfc4b.jpg)

Anki is not stopping the process

Why?

It is the only add on i have installed:
[batch-download-pictures-from-google-images](https://ankiweb.net/shared/info/561924305)

**Comment by kelciour** [comment]
It looks like it happens if there are no results. I don't know if/when it'll be fixed.

To make it less likely to happen, I can only suggest to use with two or more cards for now.

**Comment by pianoplayer15** [comment]
makes sense, appriciate your work :)

**Comment by kelciour** [comment]
Thank you for the report a while ago. It should be fixed now.
