### ISSUE TITLE
No image & Endless processing

### ISSUE THREAD

**Issue by Krixx29** [kelciour/batch-download-pictures-from-google-images#15]
Hi, I can't add images to Anki today (it still worked normally a few days ago). I'm using Anki 2.1.49.

I have 2 errors:
1. There is no image in the picture field after I add the image
2. Endless "Processing..."

I attached the output and image below. Please help.
Thank you!

[output.txt](https://github.com/kelciour/batch-download-pictures-from-google-images/files/11497733/output.txt)

![image](https://github.com/kelciour/batch-download-pictures-from-google-images/assets/106433003/c5c88ef8-2bbb-4078-8b9e-1e23dafccc56)

**Comment by judasMBit** [comment]
same for me. thanks in advance.

**Comment by usmanovbf** [comment]
Same for me

**Comment by kelciour** [comment]
Thank you for the report. I believe it's been fixed and can be closed.
