### ISSUE TITLE
Can't add batch download to my current Anki version Version ⁨2.1.65 (aa9a734f)⁩

### ISSUE THREAD

**Issue by GHESM** [kelciour/batch-download-pictures-from-google-images#17]
Dear author, 

I'm very keen on knowing how I can get your presumably awesome add-on, so I can easily add pictures to my Anki decks.
However, I get an error code when I use the add-on code or when I load the downloaded file.
I hope to hear back from you soon.

Best regards,

Ernst

**Comment by kelciour** [comment]
Thank you for the report. The add-on should now work with the latest Anki version.
