### ISSUE TITLE
Images not appearing

### ISSUE THREAD

**Issue by Hudziak68** [kelciour/batch-download-pictures-from-google-images#2]
Hello, I'm using Anki 2.1.23 on macOS Catalina.

The source field has one word in it, and the destination field is empty. When I hit Start, it processes, and then no images appear in the destination field.

Do you know why this might be? I installed the add-on directly from the Ankiweb Add-ons page.

Thank you

**Comment by kelciour** [comment]
Thank you for the report! It looks like Google changed Google Images a bit. It's been fixed and I've updated the add-on on AnkiWeb. Please use Tools - Add-ons - Check for updates.

**Comment by Hudziak68** [comment]
Thank you for fixing that so quickly!
