### ISSUE TITLE
No image comes

### ISSUE THREAD

**Issue by mepahl** [kelciour/batch-download-pictures-from-google-images#20]
Hello,
I am using anki 2.1.66  (Win 10) 
addon is the latest
User Agent configuration is set correctly
No error is coming, but also no images

Would appreciate your help.
Thank you!

**Comment by C65M** [comment]
I've the same issue on Linux.
I ran the minimal suggested on the Anki page comments section, in debug console.
I've attached the results, if that helps?
[Debug output.txt](https://github.com/kelciour/batch-download-pictures-from-google-images/files/12673174/Debug.output.txt)

**Comment by kelciour** [comment]
Thank you all for the report and the debug output. I was able to reproduce it using VPN. The add-on was updated and it should be fixed now.
