### ISSUE TITLE
No images being added

### ISSUE THREAD

**Issue by soliviantar** [kelciour/batch-download-pictures-from-google-images#22]
Hi, I just tried your addon and I am not getting any images. I am in the EU, if that matters.

Hope this can be fixed. Looks like an amazing tool!
    
```
    Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
    Platform: Windows-10-10.0.22621
    Flags: frz=True ao=True sv=3
```

**Comment by kelciour** [comment]
Run the following gist in the debug console - https://gist.github.com/kelciour/86bfa1bbcc256fbaa780ab725da14714

https://docs.ankiweb.net/misc.html#debug-console

![image](https://github.com/kelciour/batch-download-pictures-from-google-images/assets/16260735/ff2c1386-0cfa-4c13-8316-fe17b137e48c)

If it doesn't work, send me the output.

If it works, check the addon's settings, in particular the "Target Field" and "If not empty?".

![image](https://github.com/kelciour/batch-download-pictures-from-google-images/assets/16260735/9078f0e6-3f91-4fe2-aa5d-93bc60ad62c0)

**Comment by soliviantar** [comment]
The gist is giving me the 100 images found message as well. But nothing is being added to my fields. Target field is set and If not empty as well. The field is empty anyway, but I tried all three options just in case.

[Console output](https://gofile.io/d/NX6btJ) in case it is useful.

**Comment by soliviantar** [comment]
And this is the [debug console output](https://gofile.io/d/4llVOr) after running the gist. But I guess everything looks fine there.

**Comment by kelciour** [comment]
If the gist works, the add-on should work too. Maybe something wrong with the settings.

- Maybe make a new Test deck, add a few notes using the Basic note type, for example, with "cat", "dog" and "dragon" in the Front field.
- Reset the add-on settings with Tools > Add-ons > Batch Download ... > Config > Restore Defaults > OK
- Run the addon by changing the Target Field to Back and "If not empty?" to Append.

![image](https://github.com/kelciour/batch-download-pictures-from-google-images/assets/16260735/98793461-e41e-488e-bfde-8ab5bea063b2)
