### ISSUE TITLE
Add chosen file?

### ISSUE THREAD

**Issue by slabzzz** [kelciour/batch-download-pictures-from-google-images#28]
Any way to add chosen file as a link, file, etc. instead of query?

**Comment by kelciour** [comment]
Anki supports it out-of-the-box. If it doesn't work with some websites, download it to the computer first and then paste to Anki.

> You can use the paper-clip button to select audio, images, and videos from your computer's hard drive and attach them to your notes. Alternatively, you can copy the media onto your computer's clipboard (for instance, by right-clicking an image on the web and choosing 'Copy Image') and paste it into the field that you want to place it in. 
> 
> <https://docs.ankiweb.net/editing.html#editing-features>

If you meant to use with Google Reverse Image Search, it's not something that the add-on can do.
