### ISSUE TITLE
No longer pulling images

### ISSUE THREAD

**Issue by Asynonymous** [kelciour/batch-download-pictures-from-google-images#30]
I've loved this add-on and found it very useful, but within the last couple of days it's stopped being able to pull images. I'm not sure if the issue is on my end or not. I've tried disabling all other add-ons, playing around with different settings and reinstalling it, but nothing seems to have helped.
There's no errors or anything. It says processed, but no images are added to the cards. I'm lost, any ideas?

Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22000

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Batch Download Pictures From Google Images ['561924305', 2024-02-22T04:38, 'None', mod]

===IDs of active AnkiWeb add-ons===
561924305

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

Image of my set-up which used to work.
![image](https://github.com/kelciour/batch-download-pictures-from-google-images/assets/25361263/b9fabdee-a3f6-4118-8b49-05a5b4b7df8d)

**Comment by Asynonymous** [comment]
The baidu images version works (https://ankiweb.net/shared/info/1024335436) so it seems like it's an issue with google.

**Comment by Asynonymous** [comment]
Discovered something weird. If I set it to use Hanja as the source field instead of Korean or English it will sometimes actually add an image. Only sometimes though. I deleted the image and ran it again with the same settings and now no image.

![image](https://github.com/kelciour/batch-download-pictures-from-google-images/assets/25361263/08fdea11-4816-46df-9a05-f75642dc40d3)

**Comment by InfernoKing15** [comment]
Same here, doesn't work at all anymore
