### ISSUE TITLE
400 Client Error: Bad Request

### ISSUE THREAD

**Issue by Asynonymous** [kelciour/batch-download-pictures-from-google-images#31]
New error when trying to use the addon. Seems to be common based on the reviews (https://ankiweb.net/shared/info/561924305).

> 400 Client Error: Bad Request for url: https://www.google.com/search?q=anything&tbm=isch&async=_id%3Aislrg_c%2C_fmt%3Ajson&asearch=ichunklite&safe=active

Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22000

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Merge Notes ['1425504015', 2024-03-19T02:03, 'None', mod]
Batch Download Pictures From Google Images ['561924305', 2024-04-10T01:33, 'None', mod]
Paste Images As WebP ['1151815987', 2024-02-20T00:00, 'None', mod]

===IDs of active AnkiWeb add-ons===
1151815987 1425504015 561924305

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by it0na72** [comment]
having the same issue. not sure if the new version of anki broke the addon

**Comment by bense30** [comment]
I think that may be the case. I might try installing an older version of Anki and seeing if it makes a difference.

**Comment by bense30** [comment]
I saw the update and installed the new version, but I am still receiving this error:

`400 Client Error: Bad Request for url: https://www.google.com/search?q=piano&tbm=isch&async=_id%3Aislrg_c%2C_fmt%3Ajson&asearch=ichunklite&safe=active`
